[versions]
kotlin = "1.9.23"
android-gradle = "8.3.1"
ktlint-gradle = "12.1.0"
hilt = "2.50"
navigation = "2.7.7"
room = "2.6.1"
androidx-core = "1.8.0"
androidx-lifecycle = "2.4.1"
androidx-test = "1.4.0"
kotlinx-coroutine = "1.6.1"
kotlinx-serialization = "1.3.3"
retrofit = "2.9.0"

[plugins]
# kotlin
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }

# android
android-application = { id = "com.android.application", version.ref = "android-gradle" }
android-libraly = { id = "com.android.library", version.ref = "android-gradle" }

# ktlint
ktlint-gradle = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint-gradle" }

# hilt
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }

# navigation safe-args
androidx-navigation-safeargs = { id = "androidx.navigation.safeargs.kotlin", version.ref = "navigation" }

[libraries]
# coroutine
kotlinx-coroutines-bom = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-bom", version.ref = "kotlinx-coroutine" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android" }

# serialization
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization" }

# android
androidx-core = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version = "1.4.2" }
androidx-fragment = { group = "androidx.fragment", name = "fragment-ktx", version = "1.4.1" }
androidx-activity = { group = "androidx.activity", name = "activity-ktx", version = "1.4.0" }
androidx-recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version = "1.2.1" }

# navigation
androidx-navigation-runtime = { group = "androidx.navigation", name = "navigation-runtime-ktx", version.ref = "navigation" }
androidx-navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigation" }
androidx-navigation-ui = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigation" }

# lifecycle
androidx-lifecycle-viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtime = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }

# hilt
hilt-core = { group = "com.google.dagger", name = "hilt-core", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-android-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }

# room
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }

# datastore
androidx-datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version = "1.0.0" }

# material
google-material = { group = "com.google.android.material", name = "material", version = "1.6.1" }

# google play service
google-play-services-location = { group = "com.google.android.gms", name = "play-services-location", version = "20.0.0" }

# retrofit
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-kotlinx-serialization = { group = "com.jakewharton.retrofit", name = "retrofit2-kotlinx-serialization-converter", version = "0.8.0" }

# math
apache-math = { group = "org.apache.commons", name = "commons-math3", version = "3.6.1" }

# logger
timber = { group = "com.jakewharton.timber", name = "timber", version = "5.0.1" }

# map (GeoJSON)
google-maps-utils = { group = "com.google.maps.android", name = "maps-utils-ktx", version = "2.2.0" }
google-android-maps-utils = { group = "com.google.maps.android", name = "android-maps-utils", version = "2.2.0" }


# test
junit = { group = "junit", name = "junit", version = "4.13.2" }
google-truth = { group = "com.google.truth", name = "truth", version = "1.1.3" }
androidx-test-core = { group = "androidx.test", name = "core", version.ref = "androidx-test" }
androidx-test-runner = { group = "androidx.test", name = "runner", version.ref = "androidx-test" }
androidx-test-rules = { group = "androidx.test", name = "rules", version.ref = "androidx-test" }
androidx-test-junit = { group = "androidx.test.ext", name = "junit", version = "1.1.3" }
robolectric = { group = "org.robolectric", name = "robolectric", version = "4.8.1" }
mockk = { group = "io.mockk", name = "mockk", version = "1.12.5" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test" }
okhttp-mockwebserver = { group = "com.squareup.okhttp3", name = "mockwebserver", version = "4.9.3" }
